name: travel_guard
description: "A new way to travel."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  loading_animation_widget:
  provider: ^6.1.2
  flutter_osm_plugin: ^1.3.6
  location: ^8.0.0
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  latlong2: ^0.9.1
  permission_handler: ^11.1.1
  geolocator: ^13.0.2
  lottie: ^3.3.1
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  crypto: ^3.0.6
  cloud_firestore: ^5.6.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_remote_config: ^5.4.1
  cyrtranslit: ^1.0.1


  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons_json/
